/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardFinanceRouteImport } from './routes/dashboard.finance'
import { Route as DashboardActivityRouteImport } from './routes/dashboard.activity'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as AuthSigninIndexRouteImport } from './routes/auth/signin/index'
import { Route as AuthSigninTutorRouteImport } from './routes/auth/signin/tutor'
import { Route as AuthSigninElderRouteImport } from './routes/auth/signin/elder'
import { Route as AuthSignupTutorIndexRouteImport } from './routes/auth/signup/tutor/index'
import { Route as AuthSignupTutorElderSetupRouteImport } from './routes/auth/signup/tutor/elder-setup'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFinanceRoute = DashboardFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/auth/signup/',
  path: '/auth/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninIndexRoute = AuthSigninIndexRouteImport.update({
  id: '/auth/signin/',
  path: '/auth/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninTutorRoute = AuthSigninTutorRouteImport.update({
  id: '/auth/signin/tutor',
  path: '/auth/signin/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninElderRoute = AuthSigninElderRouteImport.update({
  id: '/auth/signin/elder',
  path: '/auth/signin/elder',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupTutorIndexRoute = AuthSignupTutorIndexRouteImport.update({
  id: '/auth/signup/tutor/',
  path: '/auth/signup/tutor/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupTutorElderSetupRoute =
  AuthSignupTutorElderSetupRouteImport.update({
    id: '/auth/signup/tutor/elder-setup',
    path: '/auth/signup/tutor/elder-setup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/pricing': typeof PricingRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/signin/elder': typeof AuthSigninElderRoute
  '/auth/signin/tutor': typeof AuthSigninTutorRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/signup/tutor/elder-setup': typeof AuthSignupTutorElderSetupRoute
  '/auth/signup/tutor/': typeof AuthSignupTutorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/copilot': typeof CopilotRoute
  '/pricing': typeof PricingRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/signin/elder': typeof AuthSigninElderRoute
  '/auth/signin/tutor': typeof AuthSigninTutorRoute
  '/auth/signin': typeof AuthSigninIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/auth/signup/tutor/elder-setup': typeof AuthSignupTutorElderSetupRoute
  '/auth/signup/tutor': typeof AuthSignupTutorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/pricing': typeof PricingRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/signin/elder': typeof AuthSigninElderRoute
  '/auth/signin/tutor': typeof AuthSigninTutorRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/signup/tutor/elder-setup': typeof AuthSignupTutorElderSetupRoute
  '/auth/signup/tutor/': typeof AuthSignupTutorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/copilot'
    | '/dashboard'
    | '/pricing'
    | '/dashboard/activity'
    | '/dashboard/finance'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/auth/signin/elder'
    | '/auth/signin/tutor'
    | '/auth/signin/'
    | '/auth/signup/'
    | '/auth/signup/tutor/elder-setup'
    | '/auth/signup/tutor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/copilot'
    | '/pricing'
    | '/dashboard/activity'
    | '/dashboard/finance'
    | '/dashboard/settings'
    | '/dashboard'
    | '/auth/signin/elder'
    | '/auth/signin/tutor'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/signup/tutor/elder-setup'
    | '/auth/signup/tutor'
  id:
    | '__root__'
    | '/'
    | '/copilot'
    | '/dashboard'
    | '/pricing'
    | '/dashboard/activity'
    | '/dashboard/finance'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/auth/signin/elder'
    | '/auth/signin/tutor'
    | '/auth/signin/'
    | '/auth/signup/'
    | '/auth/signup/tutor/elder-setup'
    | '/auth/signup/tutor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CopilotRoute: typeof CopilotRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PricingRoute: typeof PricingRoute
  AuthSigninElderRoute: typeof AuthSigninElderRoute
  AuthSigninTutorRoute: typeof AuthSigninTutorRoute
  AuthSigninIndexRoute: typeof AuthSigninIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
  AuthSignupTutorElderSetupRoute: typeof AuthSignupTutorElderSetupRoute
  AuthSignupTutorIndexRoute: typeof AuthSignupTutorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/finance': {
      id: '/dashboard/finance'
      path: '/finance'
      fullPath: '/dashboard/finance'
      preLoaderRoute: typeof DashboardFinanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activity': {
      id: '/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/auth/signup'
      fullPath: '/auth/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin/': {
      id: '/auth/signin/'
      path: '/auth/signin'
      fullPath: '/auth/signin/'
      preLoaderRoute: typeof AuthSigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin/tutor': {
      id: '/auth/signin/tutor'
      path: '/auth/signin/tutor'
      fullPath: '/auth/signin/tutor'
      preLoaderRoute: typeof AuthSigninTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin/elder': {
      id: '/auth/signin/elder'
      path: '/auth/signin/elder'
      fullPath: '/auth/signin/elder'
      preLoaderRoute: typeof AuthSigninElderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup/tutor/': {
      id: '/auth/signup/tutor/'
      path: '/auth/signup/tutor'
      fullPath: '/auth/signup/tutor/'
      preLoaderRoute: typeof AuthSignupTutorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup/tutor/elder-setup': {
      id: '/auth/signup/tutor/elder-setup'
      path: '/auth/signup/tutor/elder-setup'
      fullPath: '/auth/signup/tutor/elder-setup'
      preLoaderRoute: typeof AuthSignupTutorElderSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardActivityRoute: typeof DashboardActivityRoute
  DashboardFinanceRoute: typeof DashboardFinanceRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityRoute: DashboardActivityRoute,
  DashboardFinanceRoute: DashboardFinanceRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CopilotRoute: CopilotRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PricingRoute: PricingRoute,
  AuthSigninElderRoute: AuthSigninElderRoute,
  AuthSigninTutorRoute: AuthSigninTutorRoute,
  AuthSigninIndexRoute: AuthSigninIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
  AuthSignupTutorElderSetupRoute: AuthSignupTutorElderSetupRoute,
  AuthSignupTutorIndexRoute: AuthSignupTutorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
