/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ElderRouteImport } from './routes/elder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthTutorRouteImport } from './routes/auth/tutor'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const ElderRoute = ElderRouteImport.update({
  id: '/elder',
  path: '/elder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTutorRoute = AuthTutorRouteImport.update({
  id: '/auth/tutor',
  path: '/auth/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/elder': typeof ElderRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/tutor': typeof AuthTutorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/elder': typeof ElderRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/tutor': typeof AuthTutorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/elder': typeof ElderRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/tutor': typeof AuthTutorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/elder' | '/auth/login' | '/auth/tutor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/elder' | '/auth/login' | '/auth/tutor'
  id: '__root__' | '/' | '/elder' | '/auth/login' | '/auth/tutor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ElderRoute: typeof ElderRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthTutorRoute: typeof AuthTutorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/elder': {
      id: '/elder'
      path: '/elder'
      fullPath: '/elder'
      preLoaderRoute: typeof ElderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/tutor': {
      id: '/auth/tutor'
      path: '/auth/tutor'
      fullPath: '/auth/tutor'
      preLoaderRoute: typeof AuthTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ElderRoute: ElderRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthTutorRoute: AuthTutorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
