/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ElderRouteImport } from './routes/elder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as AuthSigninIndexRouteImport } from './routes/auth/signin/index'
import { Route as AuthSigninTutorRouteImport } from './routes/auth/signin/tutor'
import { Route as AuthSignupTutorIndexRouteImport } from './routes/auth/signup/tutor/index'
import { Route as AuthSignupTutorElderSetupRouteImport } from './routes/auth/signup/tutor/elder-setup'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ElderRoute = ElderRouteImport.update({
  id: '/elder',
  path: '/elder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/auth/signup/',
  path: '/auth/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninIndexRoute = AuthSigninIndexRouteImport.update({
  id: '/auth/signin/',
  path: '/auth/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninTutorRoute = AuthSigninTutorRouteImport.update({
  id: '/auth/signin/tutor',
  path: '/auth/signin/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupTutorIndexRoute = AuthSignupTutorIndexRouteImport.update({
  id: '/auth/signup/tutor/',
  path: '/auth/signup/tutor/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupTutorElderSetupRoute =
  AuthSignupTutorElderSetupRouteImport.update({
    id: '/auth/signup/tutor/elder-setup',
    path: '/auth/signup/tutor/elder-setup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/elder': typeof ElderRoute
  '/pricing': typeof PricingRoute
  '/auth/signin/tutor': typeof AuthSigninTutorRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/signup/tutor/elder-setup': typeof AuthSignupTutorElderSetupRoute
  '/auth/signup/tutor/': typeof AuthSignupTutorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/elder': typeof ElderRoute
  '/pricing': typeof PricingRoute
  '/auth/signin/tutor': typeof AuthSigninTutorRoute
  '/auth/signin': typeof AuthSigninIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/auth/signup/tutor/elder-setup': typeof AuthSignupTutorElderSetupRoute
  '/auth/signup/tutor': typeof AuthSignupTutorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/elder': typeof ElderRoute
  '/pricing': typeof PricingRoute
  '/auth/signin/tutor': typeof AuthSigninTutorRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/signup/tutor/elder-setup': typeof AuthSignupTutorElderSetupRoute
  '/auth/signup/tutor/': typeof AuthSignupTutorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/elder'
    | '/pricing'
    | '/auth/signin/tutor'
    | '/auth/signin/'
    | '/auth/signup/'
    | '/auth/signup/tutor/elder-setup'
    | '/auth/signup/tutor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/elder'
    | '/pricing'
    | '/auth/signin/tutor'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/signup/tutor/elder-setup'
    | '/auth/signup/tutor'
  id:
    | '__root__'
    | '/'
    | '/elder'
    | '/pricing'
    | '/auth/signin/tutor'
    | '/auth/signin/'
    | '/auth/signup/'
    | '/auth/signup/tutor/elder-setup'
    | '/auth/signup/tutor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ElderRoute: typeof ElderRoute
  PricingRoute: typeof PricingRoute
  AuthSigninTutorRoute: typeof AuthSigninTutorRoute
  AuthSigninIndexRoute: typeof AuthSigninIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
  AuthSignupTutorElderSetupRoute: typeof AuthSignupTutorElderSetupRoute
  AuthSignupTutorIndexRoute: typeof AuthSignupTutorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elder': {
      id: '/elder'
      path: '/elder'
      fullPath: '/elder'
      preLoaderRoute: typeof ElderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/auth/signup'
      fullPath: '/auth/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin/': {
      id: '/auth/signin/'
      path: '/auth/signin'
      fullPath: '/auth/signin/'
      preLoaderRoute: typeof AuthSigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin/tutor': {
      id: '/auth/signin/tutor'
      path: '/auth/signin/tutor'
      fullPath: '/auth/signin/tutor'
      preLoaderRoute: typeof AuthSigninTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup/tutor/': {
      id: '/auth/signup/tutor/'
      path: '/auth/signup/tutor'
      fullPath: '/auth/signup/tutor/'
      preLoaderRoute: typeof AuthSignupTutorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup/tutor/elder-setup': {
      id: '/auth/signup/tutor/elder-setup'
      path: '/auth/signup/tutor/elder-setup'
      fullPath: '/auth/signup/tutor/elder-setup'
      preLoaderRoute: typeof AuthSignupTutorElderSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ElderRoute: ElderRoute,
  PricingRoute: PricingRoute,
  AuthSigninTutorRoute: AuthSigninTutorRoute,
  AuthSigninIndexRoute: AuthSigninIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
  AuthSignupTutorElderSetupRoute: AuthSignupTutorElderSetupRoute,
  AuthSignupTutorIndexRoute: AuthSignupTutorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
